# Generated by Django 4.0.6 on 2022-08-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='rating',
            field=models.FloatField(),
        ),
    ]
