# Generated by Django 4.0.6 on 2022-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('occupation', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
