# Generated by Django 4.0.6 on 2022-08-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_guest_alter_episode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='guests',
            field=models.ManyToManyField(to='main_app.guest'),
        ),
    ]
